# Generated by Django 5.1 on 2024-08-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
