# Generated by Django 5.1 on 2024-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0004_alter_order_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='paintings/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
    ]
