# Generated by Django 5.1 on 2024-08-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0006_order1_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order1',
        ),
    ]
