# Generated by Django 5.1 on 2024-08-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.IntegerField(max_length=10),
        ),
    ]
