# Generated by Django 5.1 on 2024-08-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0009_alter_order_card_number_alter_order_cvv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
