# Generated by Django 4.2.11 on 2024-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0013_alter_paintings_artistname_alter_paintings_artname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='image',
            field=models.ImageField(upload_to='paintings/'),
        ),
    ]
