# Generated by Django 4.2.11 on 2024-08-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtAuctionSpaceApp', '0014_alter_paintings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
