# Generated by Django 4.2.11 on 2024-10-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0017_rename_price_paintings_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
    ]
