# Generated by Django 4.2.11 on 2024-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtAuctionSpaceApp', '0018_remove_order_card_number_remove_order_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintings',
            name='id',
        ),
        migrations.AlterField(
            model_name='paintings',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
